"""Framework-owned isolated worker transport primitives.

The package is intentionally presentation-, authority-, and provider-neutral.
"""

from .broker import (
    AUTH_CHALLENGE_BYTES,
    AUTH_SECRET_BYTES,
    MAX_FRAME_BYTES,
    PROTOCOL_VERSION,
    AdmissionGate,
    AdmissionLease,
    AuthenticatedSession,
    AuthenticationError,
    BootSecret,
    BrokerBusy,
    BrokerError,
    ChannelConfigurationError,
    ChannelSpec,
    Deadline,
    DeadlineExceeded,
    EndpointIdentity,
    EndpointViolation,
    FrameCodec,
    FrameEnvelope,
    PeerCredentialError,
    PeerCredentials,
    ProtocolViolation,
    ReceivedFrame,
    TransportClosed,
    TransportUncertain,
    client_handshake,
    connect_verified,
    peer_credentials,
    read_packet,
    server_handshake,
    validate_endpoint,
    write_packet,
)

__all__ = (
    "AUTH_CHALLENGE_BYTES",
    "AUTH_SECRET_BYTES",
    "MAX_FRAME_BYTES",
    "PROTOCOL_VERSION",
    "AdmissionGate",
    "AdmissionLease",
    "AuthenticatedSession",
    "AuthenticationError",
    "BootSecret",
    "BrokerBusy",
    "BrokerError",
    "ChannelConfigurationError",
    "ChannelSpec",
    "Deadline",
    "DeadlineExceeded",
    "EndpointIdentity",
    "EndpointViolation",
    "FrameCodec",
    "FrameEnvelope",
    "PeerCredentialError",
    "PeerCredentials",
    "ProtocolViolation",
    "ReceivedFrame",
    "TransportClosed",
    "TransportUncertain",
    "client_handshake",
    "connect_verified",
    "peer_credentials",
    "read_packet",
    "server_handshake",
    "validate_endpoint",
    "write_packet",
)
