"""Superseded pre-ADR-009 loopback bootstrap and browser-session authority.

This module owns no provider or tool capability.  In the pre-release development path,
the test deployment harness calls ``mint_bootstrap`` out of band, and only a same-origin
POST may exchange that capability for a short-lived cookie plus a separate CSRF value.
Session objects are live, identity-bound capabilities; constructing a dataclass with
copied fields does not authenticate it.

This harness-minted URL-fragment topology is retained only as historical loopback
feasibility evidence; it is not the current product boundary or release authentication
contract.  T025 replaces it with the self-hosted browser first-owner flow: a capability
generated by the inspectable offline deployment artifact, entered once in the browser
form and never placed in a URL, plus OriginProfile, durable session-root and recovery
design from ADR-010 through ADR-012.
"""

# ruff: noqa: PLC0414 - explicit compatibility re-exports preserve capability identity.

import ipaddress
import re
import secrets
from collections import deque
from dataclasses import dataclass
from hashlib import sha256
from threading import RLock
from uuid import uuid4

from ..domain.refs import MAX_INTEGER
from ..domain.request_identity import (
    AuthenticatedRequest as AuthenticatedRequest,
)
from ..domain.request_identity import (
    AuthenticatedSession as AuthenticatedSession,
)
from ..domain.request_identity import (
    RequestDenied as RequestDenied,
)
from ..domain.request_identity import (
    SessionBoundaryError as SessionBoundaryError,
)
from ..domain.request_identity import (
    authenticate_in_transaction as authenticate_in_transaction,
)
from ..domain.schemas import Actor

COOKIE_NAME = "deeptwin_local_session"
MAX_BOOTSTRAP_TTL_SECONDS = 60
MAX_SESSION_TTL_SECONDS = 3_600
MAX_LIVE_BOOTSTRAPS = 8
MAX_CSRF_TOKENS_PER_SESSION = 8
ATTEMPT_WINDOW_SECONDS = 60
_TOKEN = re.compile(r"[A-Za-z0-9_-]{32,256}")


class BootstrapUnavailable(SessionBoundaryError):
    pass


class BootstrapReplay(SessionBoundaryError):
    pass


@dataclass(frozen=True, slots=True)
class BootstrapCapability:
    capability: str
    expires_at: int


@dataclass(frozen=True, slots=True)
class BootstrapExchange:
    session: AuthenticatedSession
    csrf_token: str
    cookie_pair: str
    cookie_header: str
    expires_at: int


@dataclass(frozen=True, slots=True)
class RequestHeaderFields:
    host: str
    origin: str | None
    sec_fetch_site: str | None
    cookie_header: str | None
    csrf_token: str | None


@dataclass(slots=True)
class _BootstrapRecord:
    expires_at: int
    consumed_session_id: str | None = None
    expired: bool = False


@dataclass(slots=True)
class _SessionRecord:
    capability: AuthenticatedSession
    cookie_hash: str
    csrf_hashes: deque[str]
    host: str
    origin: str
    active: bool = True


def _secret_hash(value):
    if type(value) is not str:
        return ""
    try:
        return sha256(value.encode("ascii")).hexdigest()
    except UnicodeEncodeError:
        return ""


def parse_request_headers(raw_headers):
    """Extract security headers without framework last-value-wins ambiguity.

    ASGI presents headers as byte pairs.  Every security-sensitive field must be a single
    ASCII value; duplicate Host/Origin/Cookie/CSRF/fetch-metadata lines are rejected before
    any normalization or session lookup.
    """
    if type(raw_headers) not in (tuple, list) or len(raw_headers) > 256:
        raise RequestDenied("Local request headers are invalid")
    names = {
        "host": "host",
        "origin": "origin",
        "sec-fetch-site": "sec_fetch_site",
        "cookie": "cookie_header",
        "x-csrf-token": "csrf_token",
        "x-deeptwin-csrf": "csrf_token",  # the supported boundary's name; one line total
    }
    found = {value: [] for value in names.values()}
    total = 0
    for pair in raw_headers:
        if type(pair) not in (tuple, list) or len(pair) != 2:
            raise RequestDenied("Local request headers are invalid")
        name, value = pair
        if type(name) is not bytes or type(value) is not bytes:
            raise RequestDenied("Local request headers are invalid")
        total += len(name) + len(value)
        if total > 65_536:
            raise RequestDenied("Local request headers are too large")
        try:
            decoded_name = name.decode("ascii").lower()
        except UnicodeDecodeError as exc:
            raise RequestDenied("Local request header name is invalid") from exc
        field = names.get(decoded_name)
        if field is None:
            continue
        try:
            decoded_value = value.decode("ascii")
        except UnicodeDecodeError as exc:
            raise RequestDenied("Local security header value is invalid") from exc
        found[field].append(decoded_value)
    if len(found["host"]) != 1 or any(len(values) > 1 for values in found.values()):
        raise RequestDenied("Local security headers must be exact singletons")
    return RequestHeaderFields(
        found["host"][0],
        found["origin"][0] if found["origin"] else None,
        found["sec_fetch_site"][0] if found["sec_fetch_site"] else None,
        found["cookie_header"][0] if found["cookie_header"] else None,
        found["csrf_token"][0] if found["csrf_token"] else None,
    )


def _authority(value):
    if (type(value) is not str or not value.isascii() or len(value) > 64
            or any(char.isspace() or ord(char) < 0x20 for char in value)
            or any(char in value for char in "@,/?#\\[]")):
        raise ValueError("Authority must be an exact loopback host and port")
    if value.count(":") != 1:
        raise ValueError("Authority must include one explicit port")
    host, port_text = value.rsplit(":", 1)
    if (not port_text.isdecimal() or port_text.startswith("0")
            or not 1 <= int(port_text) <= 65_535):
        raise ValueError("Authority requires a canonical port")
    if host == "localhost":
        return value
    try:
        address = ipaddress.IPv4Address(host)
    except ipaddress.AddressValueError as exc:
        raise ValueError("Only canonical localhost or IPv4 loopback is accepted") from exc
    if not address.is_loopback or str(address) != host:
        raise ValueError("Only canonical IPv4 loopback is accepted")
    return value


class LocalSessionAuthority:
    """Process-local local-user session registry with an injected trusted clock."""

    def __init__(self, authorities, *, clock, session_ttl_seconds=900,
                 max_bootstrap_attempts=32):
        if type(authorities) not in (set, frozenset, tuple, list) or not authorities:
            raise ValueError("At least one explicit loopback authority is required")
        checked = tuple(_authority(value) for value in authorities)
        if len(checked) != len(set(checked)) or len(checked) > 4:
            raise ValueError("Loopback authorities must be bounded and unique")
        if not callable(clock):
            raise TypeError("A trusted clock is required")
        if (type(session_ttl_seconds) is not int
                or not 1 <= session_ttl_seconds <= MAX_SESSION_TTL_SECONDS):
            raise ValueError("Session lifetime must be finite")
        if type(max_bootstrap_attempts) is not int or not 1 <= max_bootstrap_attempts <= 128:
            raise ValueError("Bootstrap attempt bound must be 1..128")
        self.authorities = frozenset(checked)
        self._clock = clock
        self._session_ttl = session_ttl_seconds
        self._max_attempts = max_bootstrap_attempts
        self._bootstraps = {}
        self._sessions_by_cookie = {}
        self._sessions_by_id = {}
        self._attempts = deque()
        self._last_now = None
        self._lock = RLock()

    def _now(self):
        value = self._clock()
        if type(value) is not int or not 0 <= value <= MAX_INTEGER:
            raise RequestDenied("Local session clock is unavailable")
        if self._last_now is not None and value < self._last_now:
            raise RequestDenied("Local session clock moved backwards")
        self._last_now = value
        return value

    def _prune(self, now):
        while self._attempts and self._attempts[0] <= now - ATTEMPT_WINDOW_SECONDS:
            self._attempts.popleft()
        for digest, record in tuple(self._sessions_by_cookie.items()):
            if not record.active or record.capability.expires_at <= now:
                record.active = False
                self._sessions_by_cookie.pop(digest, None)
                self._sessions_by_id.pop(record.capability.session_id, None)
        for record in self._bootstraps.values():
            if record.expires_at <= now and record.consumed_session_id is None:
                record.expired = True

    def _transport(self, *, method, host, origin, sec_fetch_site, mutation):
        if type(method) is not str or method not in {"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE"}:
            raise RequestDenied("Unsupported local request method")
        try:
            candidate = _authority(host)
        except ValueError as exc:
            raise RequestDenied("Unexpected local request host") from exc
        if candidate not in self.authorities:
            raise RequestDenied("Unexpected local request host")
        expected_origin = "http://" + candidate
        if origin is not None and origin != expected_origin:
            raise RequestDenied("Unexpected local request origin")
        if mutation and origin != expected_origin:
            raise RequestDenied("A state change requires its exact local origin")
        if sec_fetch_site != "same-origin":
            raise RequestDenied("A local API request requires same-origin fetch metadata")
        return candidate, expected_origin

    def mint_bootstrap(self, *, ttl_seconds=MAX_BOOTSTRAP_TTL_SECONDS):
        if type(ttl_seconds) is not int or not 1 <= ttl_seconds <= MAX_BOOTSTRAP_TTL_SECONDS:
            raise ValueError("Bootstrap lifetime must be 1..60 seconds")
        with self._lock:
            now = self._now()
            self._prune(now)
            live = sum(not record.expired and record.consumed_session_id is None
                       and record.expires_at > now for record in self._bootstraps.values())
            if live >= MAX_LIVE_BOOTSTRAPS:
                raise BootstrapUnavailable("Too many pending development bootstrap capabilities")
            token = secrets.token_urlsafe(32)
            digest = _secret_hash(token)
            while digest in self._bootstraps:
                token = secrets.token_urlsafe(32)
                digest = _secret_hash(token)
            expires_at = now + ttl_seconds
            self._bootstraps[digest] = _BootstrapRecord(expires_at)
            return BootstrapCapability(token, expires_at)

    def exchange_bootstrap(self, capability, *, method, host, origin, sec_fetch_site):
        candidate, expected_origin = self._transport(
            method=method, host=host, origin=origin, sec_fetch_site=sec_fetch_site,
            mutation=True,
        )
        if method != "POST":
            raise RequestDenied("Only POST may establish a local session")
        with self._lock:
            now = self._now()
            self._prune(now)
            if len(self._attempts) >= self._max_attempts:
                raise BootstrapUnavailable("Bootstrap attempt capacity is exhausted")
            self._attempts.append(now)
            digest = _secret_hash(capability)
            if type(capability) is not str or _TOKEN.fullmatch(capability) is None or not digest:
                raise BootstrapUnavailable("Development bootstrap capability is unavailable")
            record = self._bootstraps.get(digest)
            if record is None:
                raise BootstrapUnavailable("Development bootstrap capability is unavailable")
            # Keep the consumed capability as a bounded replay tombstone.  A replay is
            # hostile even after the short development-bootstrap window, while its issued session
            # is still live, so revoke that session before reporting the replay.
            if record.consumed_session_id is not None:
                prior = self._sessions_by_id.get(record.consumed_session_id)
                if prior is not None:
                    self._revoke_record(prior)
                raise BootstrapReplay("Development bootstrap capability replayed; issued session revoked")
            if record.expired or record.expires_at <= now:
                if record is not None:
                    record.expired = True
                raise BootstrapUnavailable("Development bootstrap capability is unavailable")

            cookie_value = secrets.token_urlsafe(32)
            csrf_value = secrets.token_urlsafe(32)
            session = AuthenticatedSession(
                str(uuid4()), Actor(str(uuid4()), "human", "local_session"),
                now + self._session_ttl,
            )
            session_record = _SessionRecord(
                session, _secret_hash(cookie_value),
                deque((_secret_hash(csrf_value),), maxlen=MAX_CSRF_TOKENS_PER_SESSION),
                candidate, expected_origin,
            )
            record.consumed_session_id = session.session_id
            self._sessions_by_cookie[session_record.cookie_hash] = session_record
            self._sessions_by_id[session.session_id] = session_record
            pair = f"{COOKIE_NAME}={cookie_value}"
            header = (f"{pair}; Path=/; HttpOnly; SameSite=Strict; "
                      f"Max-Age={self._session_ttl}")
            return BootstrapExchange(session, csrf_value, pair, header, session.expires_at)

    @staticmethod
    def _cookie_value(cookie_header):
        if type(cookie_header) is not str or len(cookie_header) > 4_096:
            raise RequestDenied("Local session cookie is missing")
        found = []
        for item in cookie_header.split(";"):
            item = item.strip()
            if not item or "=" not in item:
                continue
            name, value = item.split("=", 1)
            if name == COOKIE_NAME:
                found.append(value)
        if len(found) != 1 or _TOKEN.fullmatch(found[0]) is None:
            raise RequestDenied("Local session cookie is invalid")
        return found[0]

    def authenticate_request(self, *, method, host, origin, sec_fetch_site,
                             cookie_header, csrf_token):
        mutation = method not in {"GET", "HEAD"}
        candidate, _ = self._transport(
            method=method, host=host, origin=origin, sec_fetch_site=sec_fetch_site,
            mutation=mutation,
        )
        cookie_value = self._cookie_value(cookie_header)
        with self._lock:
            now = self._now()
            self._prune(now)
            record = self._sessions_by_cookie.get(_secret_hash(cookie_value))
            if (record is None or not record.active or record.host != candidate
                    or record.capability.expires_at <= now):
                raise RequestDenied("Local session is not authenticated")
            if origin is not None and origin != record.origin:
                raise RequestDenied("Local session origin changed")
            csrf_verified = False
            if mutation:
                supplied = _secret_hash(csrf_token)
                matches = sum(
                    secrets.compare_digest(supplied, expected)
                    for expected in record.csrf_hashes
                ) if supplied else 0
                if matches != 1:
                    raise RequestDenied("CSRF validation failed")
                csrf_verified = True
            return AuthenticatedRequest(method, candidate, origin, record.capability, csrf_verified)

    def authenticate_bound(self, session):
        """Validate an already parsed session object for HostPolicy/command integrations."""
        if type(session) is not AuthenticatedSession:
            raise RequestDenied("Unregistered local session")
        with self._lock:
            now = self._now()
            self._prune(now)
            record = self._sessions_by_id.get(session.session_id)
            if (record is None or not record.active or record.capability is not session
                    or record.capability.expires_at <= now):
                raise RequestDenied("Unregistered or expired local session")
            return record.capability.actor

    def rotate_csrf(self, request):
        """Issue one bounded per-page token to an authenticated same-origin GET.

        A browser cookie is shared across tabs, so replacing its only CSRF value would
        silently disable every already-open page.  Keep a small FIFO of independent page
        tokens instead; opening or reloading a ninth page evicts the oldest token.
        """
        if type(request) is not AuthenticatedRequest or not request.is_read:
            raise RequestDenied("CSRF rotation requires an authenticated same-origin read")
        with self._lock:
            now = self._now()
            self._prune(now)
            record = self._sessions_by_id.get(request.session.session_id)
            if (record is None or not record.active
                    or record.capability is not request.session
                    or record.capability.expires_at <= now):
                raise RequestDenied("Local session is not authenticated")
            token = secrets.token_urlsafe(32)
            record.csrf_hashes.append(_secret_hash(token))
            return token

    def _revoke_record(self, record):
        record.active = False
        self._sessions_by_cookie.pop(record.cookie_hash, None)
        self._sessions_by_id.pop(record.capability.session_id, None)

    def revoke(self, session):
        if type(session) is not AuthenticatedSession:
            raise RequestDenied("Unregistered local session")
        with self._lock:
            record = self._sessions_by_id.get(session.session_id)
            if record is None or record.capability is not session:
                raise RequestDenied("Unregistered local session")
            self._revoke_record(record)
