"""T075: build the requirement -> task -> test -> evidence matrix from the repository.

Everything is derived from tracked files: requirement ids and summaries from spec.md,
task state and requirement citations from tasks.md, tests by the requirement ids they
cite, evidence files by the ids they cite. The matrix states only what those files
say; a requirement is "complete" only when every citing task is checked, which is a
bookkeeping state, never a claim that the requirement is met in the field.

    python specs/001-autonomous-release/tools/implementation_matrix.py > \
        specs/001-autonomous-release/evidence/implementation-matrix.md
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SPEC = ROOT / "specs/001-autonomous-release"
_REQ = re.compile(r"^- \*\*((?:FR|SC)-\d{3})\*\*: (.*)$")
_TASK = re.compile(r"^- \[([ x])\] (T\d{3})\b")
_CITE = re.compile(r"\b((?:FR|SC)-\d{3})((?:[–/]\d{3})*)")


def requirements() -> dict[str, str]:
    found = {}
    for line in (SPEC / "spec.md").read_text().splitlines():
        match = _REQ.match(line)
        if match:
            summary = match.group(2).strip()
            found[match.group(1)] = summary[:90] + ("…" if len(summary) > 90 else "")
    return found


def _cited(text: str) -> set[str]:
    ids = set()
    for match in _CITE.finditer(text):
        ids.add(match.group(1))
        prefix, previous = match.group(1)[:3], int(match.group(1)[3:])
        # "FR-010–014" is a range; "FR-013/030" lists two ids
        for separator, digits in re.findall(r"([–/])(\d{3})", match.group(2)):
            number = int(digits)
            span = range(previous + 1, number + 1) if separator == "–" else (number,)
            ids.update(f"{prefix}{item:03d}" for item in span)
            previous = number
    return ids


def tasks() -> dict[str, tuple[bool, set[str]]]:
    state: dict[str, tuple[bool, set[str]]] = {}
    current = None
    for line in (SPEC / "tasks.md").read_text().splitlines():
        match = _TASK.match(line)
        if match:
            current = match.group(2)
            state[current] = (match.group(1) == "x", _cited(line))
        elif current and line.startswith("  "):
            done, ids = state[current]
            state[current] = (done, ids | _cited(line))
        elif not line.strip():
            continue
        else:
            current = None
    return state


def _tracked(*patterns: str) -> list[Path]:
    out = subprocess.run(["git", "ls-files", *patterns], cwd=ROOT, capture_output=True, text=True, check=True)
    return [ROOT / line for line in out.stdout.splitlines()]


def citations(paths: list[Path]) -> dict[str, list[str]]:
    by_id: dict[str, list[str]] = {}
    for path in paths:
        try:
            text = path.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        for ident in _cited(text):
            by_id.setdefault(ident, []).append(path.name)
    return by_id


def build() -> str:
    reqs = requirements()
    task_state = tasks()
    tests = citations(_tracked("app/tests/test_*.py", "app/tests/*.test.mjs", "evals/deeptwin/tests/test_*.py"))
    evidence = citations(_tracked("specs/001-autonomous-release/evidence/*.md"))
    lines = [
        "# Implementation matrix (T075, generated)",
        "",
        "Generated by `specs/001-autonomous-release/tools/implementation_matrix.py` from spec.md, tasks.md,",
        "the tracked tests and evidence. \"complete\" means every task citing the requirement is checked in",
        "tasks.md; it is bookkeeping, not a field claim. A requirement with open tasks lists them; one no",
        "task cites is flagged. Test and evidence columns count files that cite the id.",
        "",
        "| Req | Summary | Tasks done | Open tasks | Tests | Evidence | State |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    totals = {"complete": 0, "open": 0, "uncited": 0}
    for ident, summary in reqs.items():
        citing = sorted(t for t, (_d, ids) in task_state.items() if ident in ids)
        done = [t for t in citing if task_state[t][0]]
        open_ = [t for t in citing if not task_state[t][0]]
        state = "uncited" if not citing else ("open" if open_ else "complete")
        totals[state] += 1
        summary = summary.replace("|", "\\|")
        lines.append(
            f"| {ident} | {summary} | {len(done)} | {', '.join(open_) or '—'} | "
            f"{len(tests.get(ident, []))} | {len(evidence.get(ident, []))} | {state} |"
        )
    open_tasks = sorted(t for t, (d, _i) in task_state.items() if not d)
    lines += [
        "",
        f"Requirements: {len(reqs)} — complete {totals['complete']}, open {totals['open']}, "
        f"uncited {totals['uncited']}. Tasks: {len(task_state)} — done "
        f"{len(task_state) - len(open_tasks)}, open {len(open_tasks)}.",
        "",
        "Open tasks: " + ", ".join(open_tasks) + ".",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(build(), end="")
